GET http://127.0.0.1:8000/api/produits
Accept: application/json        


###

GET http://127.0.0.1:8000/api/categories
Accept: application/json        


###


POST http://127.0.0.1:8000/api/categories
Accept: application/json        
Content-Type: application/json

{
    "catNom": "string"
}

###


POST http://127.0.0.1:8000/api/produits
Accept: application/json        
Content-Type: application/json

{
    "proNom": "string",
    "proPrix": "12.55",
    "cat": "/api/categories/1"
}
